# docker-compose.yml

version: '3.8'
services:
  postgres:
    image: postgres:16
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: coin_tab_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    name: coin_tab_db_data
